language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
notifications:
  email:
    - nickjohnson-dev@gmail.com
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
    - stage: deploy-to-chromatic
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx chromatic --exit-zero-on-changes
        on:
          all_branches: true
